version: "3.7"

services:
  back:
    build:
      context: .
      dockerfile: hseling_api_judgment/Dockerfile
    volumes:
      - ./sudact_database/sudact.sqlite:/app/sudact.sqlite
    ports:
      - 5000:80
  front:
      env_file: hseling_web_judgment/environment.env
      build:
        context: .
        dockerfile: hseling_web_judgment/Dockerfile
        args:
          - django_secret_key=igl+d2j%bp=mebuk7dd-6y84fh*#h4pgf*nkx#zv#=ucvl8hhe
      ports:
        - 8000:80

